	- name: Run Python Script
	uses: jannekem/run-python-script-action@v1.7
  with:
    # Python script
    script: main.py
    # Fail step if the return code from running the script is non-zero
    fail-on-error: # optional, default is true
    # Include utility functions
    util: # optional, default is true
          
