            - name: Run Python Script
  # You may pin to the exact commit or the version.
  # uses: jannekem/run-python-script-action@bbfca66c612a28f3eeca0ae40e1f810265e2ea68
  uses: jannekem/run-python-script-action@v1.7
  with:
    # Python script
    script: main.py
    # Fail step if the return code from running the script is non-zero
    fail-on-error: # optional, default is true
    # Include utility functions
    util: # optional, default is true
          
